/**
 * Extracts the third-party extension contract's type surface as a stable,
 * human-readable report. Consumed two ways:
 *
 *   - `scripts/api-surface-report.ts` regenerates docs/API_SURFACE.md after a
 *     DELIBERATE contract change;
 *   - `src/__tests__/api-surface.test.ts` re-derives the report and asserts it
 *     matches the committed file, so an accidental signature change reddens CI.
 *
 * The pinned names are the surface DOMAIN_AUTHOR_GUIDE.md promises to domain
 * authors (now living in the external lokascript-domains repo): the DSL
 * factory, the schema helpers, the descriptor/extension shapes, and
 * DomainRegistry.register.
 */
import ts from 'typescript';
import path from 'node:path';

export const PINNED_EXPORTS = [
  'createMultilingualDSL',
  'defineCommand',
  'defineRole',
  'DomainDescriptor',
  'MultilingualDSL',
  'DomainExtension',
] as const;

const FLAGS =
  ts.TypeFormatFlags.NoTruncation | ts.TypeFormatFlags.UseAliasDefinedOutsideCurrentScope;

export function extractApiSurface(pkgRoot: string): string {
  const entry = path.join(pkgRoot, 'src', 'index.ts');
  const configFile = ts.readConfigFile(path.join(pkgRoot, 'tsconfig.json'), ts.sys.readFile);
  const parsed = ts.parseJsonConfigFileContent(configFile.config, ts.sys, pkgRoot);
  const program = ts.createProgram({
    rootNames: [entry],
    options: { ...parsed.options, noEmit: true, skipLibCheck: true },
  });
  const checker = program.getTypeChecker();
  const source = program.getSourceFile(entry);
  if (!source) throw new Error(`cannot load ${entry}`);
  const moduleSymbol = checker.getSymbolAtLocation(source);
  if (!moduleSymbol) throw new Error('entry has no module symbol');
  const exports = checker.getExportsOfModule(moduleSymbol);

  const resolve = (sym: ts.Symbol): ts.Symbol =>
    sym.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(sym) : sym;

  const lines: string[] = [
    '# @lokascript/framework — pinned extension-contract surface',
    '',
    'Generated by `npx tsx scripts/api-surface-report.ts` (run from packages/framework).',
    'Asserted verbatim by `src/__tests__/api-surface.test.ts` — regenerate and commit',
    'ONLY for a deliberate contract change, and note it in DOMAIN_AUTHOR_GUIDE.md.',
    '',
  ];

  const describeMembers = (type: ts.Type, location: ts.Node): string[] => {
    const out: string[] = [];
    for (const prop of [...type.getProperties()].sort((a, b) => a.name.localeCompare(b.name))) {
      const propType = checker.getTypeOfSymbolAtLocation(prop, location);
      const optional = prop.flags & ts.SymbolFlags.Optional ? '?' : '';
      out.push(`- \`${prop.name}${optional}: ${checker.typeToString(propType, location, FLAGS)}\``);
    }
    return out;
  };

  for (const name of PINNED_EXPORTS) {
    lines.push(`## ${name}`, '');
    const exported = exports.find(s => s.name === name);
    if (!exported) {
      lines.push('**MISSING FROM PUBLIC EXPORTS**', '');
      continue;
    }
    const sym = resolve(exported);

    if (sym.valueDeclaration) {
      const type = checker.getTypeOfSymbolAtLocation(sym, sym.valueDeclaration);
      const signatures = type.getCallSignatures();
      if (signatures.length > 0) {
        for (const sig of signatures) {
          lines.push(`\`\`\`ts`, checker.signatureToString(sig, sym.valueDeclaration, FLAGS), '```');
        }
        lines.push('');
        continue;
      }
    }

    // Interface / type alias: list members with resolved types.
    const declared = checker.getDeclaredTypeOfSymbol(sym);
    const location = sym.declarations?.[0] ?? source;
    lines.push(...describeMembers(declared, location), '');
  }

  // DomainRegistry.register — the registration entry point domain packages call.
  lines.push('## DomainRegistry.register', '');
  const registrySym = exports.find(s => s.name === 'DomainRegistry');
  if (!registrySym) {
    lines.push('**MISSING FROM PUBLIC EXPORTS**', '');
  } else {
    const sym = resolve(registrySym);
    const instanceType = checker.getDeclaredTypeOfSymbol(sym);
    const register = instanceType.getProperty('register');
    if (!register) {
      lines.push('**DomainRegistry has no `register` member**', '');
    } else {
      const location = register.valueDeclaration ?? sym.declarations?.[0] ?? source;
      const type = checker.getTypeOfSymbolAtLocation(register, location);
      for (const sig of type.getCallSignatures()) {
        lines.push('```ts', `register${checker.signatureToString(sig, location, FLAGS)}`, '```');
      }
      lines.push('');
    }
  }

  // Prettier-idempotent output (the repo's lint-staged hook formats committed
  // markdown): exactly one trailing newline, no trailing blank line — a
  // formatter pass over the committed snapshot must be a no-op or the test
  // compares against a file the generator can no longer reproduce.
  return lines.join('\n').replace(/\n+$/, '');
}
