/**
 * Generator
 *
 * Emits the virtual `hyperfixi` module: a bundle on `@hyperfixi/engine` that
 * registers only the grammar modules the scanned project needs. A bundle on the
 * engine IS the list passed to `register()`, so there is one tier: the modules.
 * (Until 4.0 the generator embedded one of core's three parsers — regex "lite",
 * the hybrid AST parser, or a fallback to the full `hyperfixi.js` — each with its
 * own semantics; measured 2026-10-03: lite 3.9–4.5 KB, hybrid 12.3–16.1 KB, the
 * fallback 352 KB, which any use of `fetch` reached. On the engine the same
 * usages are 17–20 KB and `everything` is 34 KB, all with upstream's grammar.)
 *
 * Multilingual: text is the interchange. When semantic parsing is enabled the
 * bundle translates a non-English script to English as the engine reads it
 * (`api.addSourceTransform`); the attribute stays as written.
 */

import type { AggregatedUsage, HyperfixiPluginOptions } from './types';
import { resolveModules, type ModuleUsage } from './engine-modules';
import {
  resolveSemanticConfig,
  generateSemanticIntegrationCode,
  getSemanticExports,
  getSemanticBundleSize,
  type SemanticConfig,
} from './semantic-integration';

// =============================================================================
// BUNDLE GENERATOR
// =============================================================================

interface BundleSpec {
  name: string;
  /** Engine module export names, in registration order. */
  modules: string[];
  /** For the header and `api.bundle`: what the scan saw. */
  commands: string[];
  blocks: string[];
  positional: boolean;
  reactivity: boolean;
  /** Re-process content htmx swaps in (`htmx:load` / `htmx:afterSettle`). */
  htmxIntegration: boolean;
  globalName: string;
  autoInit: boolean;
  esModule: boolean;
  semantic: SemanticConfig;
}

const ENGINE_API_NAMES = ['api', 'boot', 'register'];

/**
 * Generate the bundle source from a spec.
 */
function generateBundleCode(spec: BundleSpec): string {
  const {
    name,
    modules,
    commands,
    blocks,
    positional,
    reactivity,
    htmxIntegration,
    globalName,
    autoInit,
    esModule,
    semantic,
  } = spec;

  const semanticCode = generateSemanticIntegrationCode(semantic);
  const semanticExports = getSemanticExports(semantic);
  const languages = semantic.enabled ? [...semantic.languages].sort() : [];

  const headerLines = [
    `Modules: ${modules.join(', ')}`,
    commands.length > 0 ? `Commands: ${commands.join(', ')}` : '',
    blocks.length > 0 ? `Blocks: ${blocks.join(', ')}` : '',
    positional ? 'Expressions: positional / collection (expressionsExtra)' : '',
    reactivity ? 'Reactivity: live / when / bind' : '',
    semantic.enabled
      ? `Multilingual: ${languages.join(', ') || 'en'} (translated as read, through the engine's source transform)`
      : '',
    htmxIntegration ? 'htmx: content swapped in is processed (htmx:load / htmx:afterSettle)' : '',
  ].filter(Boolean);

  const bundleInfo = JSON.stringify({
    generator: '@hyperfixi/vite-plugin',
    modules,
    commands,
    blocks,
    languages,
  });

  const apiProps = [`bundle: ${bundleInfo}`, ...semanticExports].map(p => `  ${p},`).join('\n');

  // `boot()` installs `window._hyperscript` (the engine is a _hyperscript
  // implementation; that global is its to take) and processes the document.
  // The plugin's own global is set beside it unless the two names coincide.
  const installGlobal = globalName === '_hyperscript' ? '' : `  window.${globalName} = api;\n`;

  const htmxHooks = htmxIntegration
    ? `
  // htmx (any major) announces swapped-in content on these; hand it to the engine.
  for (const type of ['htmx:load', 'htmx:afterSettle']) {
    document.addEventListener(type, event => {
      const detail = event.detail;
      const target = (detail && (detail.elt || detail.target)) || event.target;
      if (target instanceof Element) api.processNode(target);
    });
  }
`
    : '';

  return `/**
 * hyperfixi ${name} bundle (auto-generated)
 *
 * Generated by: @hyperfixi/vite-plugin
 * Engine: @hyperfixi/engine — the grammar is exactly the modules registered below.
${headerLines.map(l => ` * ${l}`).join('\n')}
 *
 * DO NOT EDIT - This file is automatically regenerated.
 */

import { ${[...ENGINE_API_NAMES, ...modules].join(', ')} } from '@hyperfixi/engine';
${semanticCode}
register(${modules.join(', ')});
${semantic.enabled ? 'api.addSourceTransform(translateSource);\n' : ''}
Object.assign(api, {
${apiProps}
});
${
  autoInit
    ? `
if (typeof window !== 'undefined') {
${installGlobal}  boot();
${htmxHooks}}
`
    : ''
}${
    esModule
      ? `
export default api;
export { api };
`
      : ''
  }`;
}

// =============================================================================
// GENERATOR CLASS
// =============================================================================

/**
 * Generator class for creating module-list bundles on the engine
 */
export class Generator {
  private debug: boolean;

  constructor(options: Pick<HyperfixiPluginOptions, 'debug'>) {
    this.debug = options.debug ?? false;
  }

  /**
   * Generate bundle code from aggregated usage
   */
  generate(usage: AggregatedUsage, options: HyperfixiPluginOptions): string {
    const commands = [...new Set([...usage.commands, ...(options.extraCommands ?? [])])];
    const blocks = [...new Set([...usage.blocks, ...(options.extraBlocks ?? [])])];
    const positional = usage.positional || options.positional || false;
    const reactivity = Boolean(
      usage.needsReactivity || usage.needsBindToProperty || usage.htmx?.needsReactivity
    );

    // Resolve semantic configuration
    const semantic = resolveSemanticConfig(options, usage.detectedLanguages);

    // If no usage detected and no semantic, return empty module
    if (
      commands.length === 0 &&
      blocks.length === 0 &&
      !positional &&
      !reactivity &&
      !semantic.enabled
    ) {
      return this.generateEmptyBundle(options);
    }

    const moduleUsage: ModuleUsage = {
      commands,
      blocks,
      positional,
      reactivity,
      construct: usage.needsConstruct,
      cookies: usage.needsCookies,
    };
    const { modules, unknown } = resolveModules(moduleUsage);

    if (this.debug) {
      if (unknown.length > 0) {
        console.log(
          `[hyperfixi] Scanned names with no engine module (a form the engine dropped, or a false positive): ${unknown.join(', ')}`
        );
      }
      if (usage.htmx?.needsHxLive || usage.htmx?.needsSSE || usage.htmx?.needsWS) {
        console.log(
          '[hyperfixi] hx-live / sse-* / ws-* attributes seen: these are htmx 4 features on the engine ' +
            '(load htmx 4 beside this bundle; a hyperscript-bodied hx-live is a `live … end` block).'
        );
      }
      const bundleInfo: Record<string, unknown> = {
        modules,
        commands,
        blocks,
        positional,
        reactivity,
      };
      if (semantic.enabled && semantic.bundleType) {
        const sizeInfo = getSemanticBundleSize(semantic.bundleType);
        bundleInfo.semanticBundle = semantic.bundleType;
        bundleInfo.semanticSize = sizeInfo.gzip;
        bundleInfo.languages = [...semantic.languages];
        bundleInfo.grammar = semantic.grammarEnabled;
      }
      console.log('[hyperfixi] Generating bundle:', bundleInfo);
      if (semantic.bundleType === 'all' || semantic.bundleType === 'priority') {
        console.log(
          `[hyperfixi] Note: Using '${semantic.bundleType}' semantic bundle (${getSemanticBundleSize(semantic.bundleType).gzip}). ` +
            `Consider using 'region' option to select a smaller regional bundle if all languages aren't needed.`
        );
      }
    }

    return generateBundleCode({
      name: options.bundleName ?? 'ViteAutoGenerated',
      modules,
      commands,
      blocks,
      positional,
      reactivity,
      htmxIntegration: options.htmx ?? usage.htmx?.hasHtmxAttributes ?? false,
      globalName: options.globalName ?? 'hyperfixi',
      autoInit: true,
      esModule: true,
      semantic,
    });
  }

  /**
   * Generate an empty bundle when no hyperscript is detected
   */
  private generateEmptyBundle(options: HyperfixiPluginOptions): string {
    const globalName = options.globalName ?? 'hyperfixi';

    return `/**
 * hyperfixi Empty Bundle (Auto-Generated)
 *
 * No hyperscript usage detected. This bundle provides a minimal API.
 * Add hyperscript attributes (_="...") to your HTML to enable features.
 *
 * Generated by: @hyperfixi/vite-plugin
 */

const api = {
  version: '1.0.0-empty',
  bundle: { generator: '@hyperfixi/vite-plugin', modules: [], commands: [], blocks: [], languages: [] },

  parse() {
    console.warn('hyperfixi: No engine loaded. Add hyperscript to your HTML to enable parsing.');
    return { errors: [] };
  },

  async evaluate(code, element) {
    console.warn('hyperfixi: No modules loaded. Detected commands will be automatically included.');
    return null;
  },

  processNode() {},
  process() {},
};

if (typeof window !== 'undefined') {
  window.${globalName} = api;
}

export default api;
export { api };
`;
  }

  /**
   * Generate a development fallback bundle: the engine with every module.
   *
   * One shape serves every former fallback (`hybrid-complete`, `full`, `hx-v4`):
   * the engine's `everything` is 34 KB gzipped and carries the reactive features
   * (`live`, `when`, `bind`) the hx-v4 fallback existed for. The argument is kept
   * for the option's type; its value no longer changes the output.
   */
  generateDevFallback(
    _fallback: 'hybrid-complete' | 'full' | 'hx-v4' | 'everything' = 'everything'
  ): string {
    return `/**
 * hyperfixi Dev Fallback Bundle
 *
 * The engine with every module, for faster development rebuilds.
 * Production builds register only the modules the project uses.
 *
 * Generated by: @hyperfixi/vite-plugin
 */

import { api, boot, register, everything } from '@hyperfixi/engine';

register(...everything);
Object.assign(api, {
  bundle: { generator: '@hyperfixi/vite-plugin', modules: ['everything'], commands: [], blocks: [], languages: [] },
});

if (typeof window !== 'undefined') {
  window.hyperfixi = api;
  boot();
}

export default api;
export { api };
`;
  }
}
