/**
 * Vite Plugin Types
 *
 * Type definitions for the HyperFixi Vite plugin.
 */

/**
 * Options for the HyperFixi Vite plugin
 */
export interface HyperfixiPluginOptions {
  /**
   * @deprecated Removed in 4.0. `'compile'` pre-compiled handlers to JS with
   * `@hyperfixi/core`'s parser; it went with that parser, and the plugin always emits the
   * engine-module bundle now (setting `'compile'` logs a warning and does that).
   */
  mode?: 'interpret' | 'compile';

  /**
   * File patterns to scan for hyperscript usage.
   * Defaults to common web file extensions.
   */
  include?: RegExp | string[];

  /**
   * File patterns to exclude from scanning.
   * Defaults to node_modules.
   */
  exclude?: RegExp | string[];

  /**
   * Extra commands to always include in the bundle.
   * Use this for dynamically generated hyperscript that can't be detected.
   */
  extraCommands?: string[];

  /**
   * Extra blocks to always include in the bundle.
   */
  extraBlocks?: string[];

  /**
   * Always include positional expressions (first, last, next, closest, parent).
   * Set to true if your dynamic code uses these.
   */
  positional?: boolean;

  /**
   * Hand content htmx swaps in to the engine (`htmx:load` / `htmx:afterSettle`
   * → `processNode`). On by default when the scan finds htmx attributes.
   * htmx itself is not bundled: load htmx 4 beside the generated bundle.
   */
  htmx?: boolean;

  /**
   * Development mode fallback strategy.
   * - 'everything': the engine with every module (34 KB gzipped), for faster dev rebuilds
   * - 'auto': generate the module-list bundle in dev too
   * - 'hybrid-complete' | 'full': accepted for compatibility; both mean 'everything'
   *   (core's prebuilt bundles are no longer what the plugin falls back to)
   */
  devFallback?: 'everything' | 'hybrid-complete' | 'full' | 'auto';

  /**
   * Global variable name for the hyperfixi API.
   * Defaults to 'hyperfixi'.
   */
  globalName?: string;

  /**
   * Bundle name for generated code comments.
   * Defaults to 'ViteAutoGenerated'.
   */
  bundleName?: string;

  /**
   * Enable verbose logging during development.
   */
  debug?: boolean;

  // =========================================================================
  // Server Bridge Options
  // =========================================================================

  /**
   * Enable server-bridge route generation alongside bundle generation.
   * Requires `@hyperfixi/server-bridge` to be installed as a peer dependency.
   * If not installed, a warning is logged and the feature is silently skipped.
   *
   * @example
   * ```typescript
   * hyperfixi({
   *   serverBridge: {
   *     framework: 'express',
   *     output: './server/routes',
   *   }
   * })
   * ```
   */
  serverBridge?: ServerBridgeOptions;

  // =========================================================================
  // Multilingual Semantic Options
  // =========================================================================

  /**
   * Enable semantic parsing for multilingual support.
   * - false: No semantic parsing (default, current behavior)
   * - true: Auto-detect languages from templates
   * - 'en': English semantic only (synonyms, flexible syntax)
   * - 'auto': Same as true
   */
  semantic?: boolean | 'en' | 'auto';

  /**
   * Explicit language list (overrides auto-detection).
   * Use ISO 639-1 codes: 'en', 'es', 'ja', 'ko', 'zh', 'ar', etc.
   */
  languages?: string[];

  /**
   * Regional bundle shorthand (alternative to explicit languages).
   * - 'western': en, es, pt, fr, de, it
   * - 'east-asian': ja, zh, ko
   * - 'slavic': pl, ru, uk
   * - 'south-asian': hi, bn
   * - 'priority': 13 most common languages
   * - 'all': All 24 supported languages
   */
  region?: 'western' | 'east-asian' | 'slavic' | 'south-asian' | 'priority' | 'all';

  /**
   * Enable grammar transformation for native word order.
   * When true, semantic is automatically enabled.
   * Adds support for SOV (Japanese, Korean) and VSO (Arabic) word orders.
   */
  grammar?: boolean;

  /**
   * Always include these languages in addition to detected ones.
   * Useful for dynamic content not detectable at build time.
   */
  extraLanguages?: string[];

  // =========================================================================
  // Multi-Domain Options
  // =========================================================================

  /**
   * Register additional domains for scanning.
   * Each domain declares its attribute patterns and keywords for detection.
   * Runs alongside the default hyperscript scanner.
   *
   * @example
   * ```typescript
   * hyperfixi({
   *   domains: [
   *     {
   *       domain: 'sql',
   *       attributes: ['data-sql'],
   *       scriptTypes: ['text/sql-dsl'],
   *       keywords: { en: ['select', 'insert', 'update', 'delete'] },
   *     },
   *   ],
   * })
   * ```
   */
  domains?: DomainScanRule[];

  /**
   * Custom language keyword definitions.
   * Use this to add new languages or extend/override existing keyword detection.
   *
   * @example
   * ```typescript
   * hyperfixi({
   *   customKeywords: {
   *     // Add a new language
   *     'my-lang': {
   *       keywords: new Set(['mytoggle', 'myadd', 'myremove']),
   *       isNonLatin: false,
   *     },
   *     // Extend an existing language with additional keywords
   *     'es': {
   *       keywords: new Set(['conmutar', 'intercambiar']),  // Additional Spanish keywords
   *       extend: true,  // Merge with existing keywords
   *     },
   *   },
   * })
   * ```
   */
  customKeywords?: Record<string, CustomLanguageKeywords>;
}

/**
 * Custom language keyword configuration.
 */
export interface CustomLanguageKeywords {
  /**
   * Set of keywords for this language.
   */
  keywords: Set<string>;

  /**
   * Whether this language uses non-Latin script.
   * Non-Latin scripts use simple substring matching (no word boundaries).
   * Latin scripts use word boundary matching to avoid false positives.
   */
  isNonLatin?: boolean;

  /**
   * If true, merge these keywords with existing ones for this language.
   * If false (default), replace existing keywords entirely.
   */
  extend?: boolean;
}

/**
 * HTMX/Fixi attribute usage information
 */
export interface HtmxUsage {
  /** Whether any htmx attributes were found */
  hasHtmxAttributes: boolean;

  /** Whether any fixi-specific attributes were found (fx-action, etc.) */
  hasFixiAttributes: boolean;

  /** HTTP methods used (GET, POST, PUT, PATCH, DELETE) */
  httpMethods: Set<string>;

  /** Swap strategies used (innerHTML, morph, delete, beforeend, etc.) */
  swapStrategies: Set<string>;

  /** hx-on:* handler values (raw hyperscript) */
  onHandlers: string[];

  /** Trigger modifiers detected (debounce, throttle, once) */
  triggerModifiers: Set<string>;

  /** URL management strategies (push-url, replace-url) */
  urlManagement: Set<string>;

  /** Whether hx-confirm is used */
  usesConfirm: boolean;

  /**
   * `hx-swap` carries a `swap:`/`settle:` timing modifier, which the translator
   * emits as `wait <n>ms`. Optional so older fixture literals stay valid.
   */
  needsSwapTiming?: boolean;

  /**
   * htmx v4 reactive/streaming surface detected. `needsHxLive` pulls in the
   * engine's reactivity modules; htmx itself is not bundled (core's
   * hyperfixi-hx-v4.js, the premade bundle for this surface, retired in C3).
   *
   * Optional to keep older fixture literals (and callers that ignore
   * htmx v4) compatible. Scanner code always emits explicit `false`.
   */
  needsHxLive?: boolean;
  /** sse-connect / sse-swap detected. Detection only: SSE is htmx 4's (core's htmx layer retired in C3). */
  needsSSE?: boolean;
  /** ws-connect / ws-send detected. Detection only: WebSockets are htmx 4's. */
  needsWS?: boolean;
  /**
   * `bind $x to <expr>.<prop>` detected inside an `_=` attribute. Implies
   * reactivity (the bind feature lives in `@hyperfixi/reactivity`).
   */
  needsBindToProperty?: boolean;
  /**
   * Any reactive feature → the generated bundle registers the engine's
   * reactivity modules. Derived from needsHxLive || needsBindToProperty.
   */
  needsReactivity?: boolean;
}

/**
 * Usage information detected from a single file
 */
export interface FileUsage {
  /** Commands used in this file */
  commands: Set<string>;

  /** Block types used (if, repeat, for, while, fetch) */
  blocks: Set<string>;

  /** Whether positional expressions are used */
  positional: boolean;

  /** Non-English languages detected in hyperscript (ISO 639-1 codes) */
  detectedLanguages: Set<string>;

  /** HTMX/Fixi attribute usage (if detected) */
  htmx?: HtmxUsage;

  /**
   * Reactivity-requiring constructs detected directly inside `_=` script
   * bodies (independent of htmx attributes): the engine's `live` / `when` /
   * `bind` features and the `^var` form. When true, the generated bundle
   * registers the engine's `reactivity` (and `liveTemplates`) modules.
   *
   * Kept top-level rather than under `htmx` because authors may use these
   * features without any htmx attributes at all (pure `_=` reactive code).
   * The aggregator OR-merges this with `htmx.needsReactivity`.
   *
   * Optional so older callers / fixtures that build `FileUsage` literals
   * without these fields stay valid; the scanner always emits explicit
   * `false` so reads can rely on the value being defined post-scan.
   */
  needsReactivity?: boolean;

  /**
   * Explicit-property `bind` form (`bind $x to <expr>.<prop>`) detected
   * in an `_=` body. Implies `needsReactivity` too.
   */
  needsBindToProperty?: boolean;

  /** `new X(…)` seen: the engine's `construct` addition is registered. */
  needsConstruct?: boolean;

  /** `cookies` seen: the engine's `cookies` expression module is registered. */
  needsCookies?: boolean;
}

/**
 * Aggregated usage information across all files
 */
export interface AggregatedUsage {
  /** All commands detected across all files */
  commands: Set<string>;

  /** All blocks detected across all files */
  blocks: Set<string>;

  /** Whether any file uses positional expressions */
  positional: boolean;

  /** All non-English languages detected across all files */
  detectedLanguages: Set<string>;

  /** Aggregated HTMX/Fixi usage across all files */
  htmx: HtmxUsage;

  /**
   * Whether any file uses reactivity-requiring constructs (either via
   * `hx-live` attributes or inside `_=` scripts). Drives the generated
   * bundle's auto-install of `@hyperfixi/reactivity`.
   *
   * Optional to keep test fixtures compatible; the aggregator always
   * emits an explicit boolean.
   */
  needsReactivity?: boolean;

  /** Whether any file uses explicit-property bind. */
  needsBindToProperty?: boolean;

  /** Whether any file uses `new X(…)` (the engine's `construct` addition). */
  needsConstruct?: boolean;

  /** Whether any file reads `cookies`. */
  needsCookies?: boolean;

  /** Map of file paths to their usage */
  fileUsage: Map<string, FileUsage>;
}

/**
 * Information about a script that needs compilation
 */
export interface ScriptLocation {
  /** File path where the script was found */
  file: string;

  /** The hyperscript code */
  script: string;

  /** Line number in the file (for source maps) */
  line?: number;

  /** Column number in the file */
  column?: number;
}

/**
 * Aggregated scripts for compilation mode
 */
export interface AggregatedScripts {
  /** All unique scripts found across all files */
  scripts: Map<string, ScriptLocation[]>;

  /** Map of file paths to scripts in that file */
  fileScripts: Map<string, string[]>;
}

// =============================================================================
// Multi-Domain Scanning
// =============================================================================

/**
 * Configuration for a domain's scanning rules in the Vite plugin.
 */
export interface DomainScanRule {
  /** Domain name */
  readonly domain: string;
  /** Attribute names to scan for (e.g., ['data-sql', '_sql']) */
  readonly attributes: readonly string[];
  /** Script tag types to scan for (e.g., ['text/sql-dsl']) */
  readonly scriptTypes?: readonly string[];
  /** Keywords for command detection, keyed by language code */
  readonly keywords?: Readonly<Record<string, readonly string[]>>;
}

/**
 * Per-domain usage detected in a single file.
 */
export interface DomainFileUsage {
  /** Domain name */
  readonly domain: string;
  /** Detected keywords/commands */
  readonly detectedKeywords: Set<string>;
  /** Languages detected */
  readonly detectedLanguages: Set<string>;
  /** Number of snippets found */
  readonly snippetCount: number;
}

/**
 * Aggregated usage across all files for a single domain.
 */
export interface DomainAggregatedUsage {
  /** Domain name */
  readonly domain: string;
  /** All detected keywords across files */
  readonly detectedKeywords: Set<string>;
  /** All detected languages across files */
  readonly detectedLanguages: Set<string>;
  /** Number of files with this domain's usage */
  readonly fileCount: number;
  /** Total snippets across all files */
  readonly totalSnippets: number;
}

// =============================================================================
// Server Bridge Integration
// =============================================================================

/**
 * Options for server-bridge route generation.
 */
export interface ServerBridgeOptions {
  /** Target server framework (default: 'express') */
  framework?: 'express' | 'hono' | 'openapi' | 'django' | 'fastapi';
  /** Output directory for generated route files (default: './server/routes') */
  output?: string;
  /** Generate TypeScript (default: true) */
  typescript?: boolean;
  /** URL patterns to ignore */
  ignore?: string[];
}
