/**
 * Vite Plugin Types
 *
 * Type definitions for the HyperFixi Vite plugin.
 */

/**
 * Options for the HyperFixi Vite plugin
 */
export interface HyperfixiPluginOptions {
  /**
   * Bundle generation mode:
   * - 'interpret': Generate minimal bundle with parser (default, ~8KB gzip)
   * - 'compile': Pre-compile hyperscript to JS at build time (~500 bytes gzip)
   *
   * Compile mode limitations:
   * - No dynamic hyperscript (runtime execute() won't work)
   * - No block commands (if, for, repeat, while, fetch)
   * - HTML must be transformed to use data-h attributes
   *
   * Use compile mode when:
   * - Bundle size is critical (<1KB target)
   * - All hyperscript is static (no dynamic generation)
   * - Only simple commands are used (toggle, add, remove, set, etc.)
   */
  mode?: 'interpret' | 'compile';

  /**
   * File patterns to scan for hyperscript usage.
   * Defaults to common web file extensions.
   */
  include?: RegExp | string[];

  /**
   * File patterns to exclude from scanning.
   * Defaults to node_modules.
   */
  exclude?: RegExp | string[];

  /**
   * Extra commands to always include in the bundle.
   * Use this for dynamically generated hyperscript that can't be detected.
   */
  extraCommands?: string[];

  /**
   * Extra blocks to always include in the bundle.
   */
  extraBlocks?: string[];

  /**
   * Always include positional expressions (first, last, next, closest, parent).
   * Set to true if your dynamic code uses these.
   */
  positional?: boolean;

  /**
   * Enable HTMX integration (auto-process after htmx:afterSettle).
   */
  htmx?: boolean;

  /**
   * Development mode fallback strategy.
   * - 'hybrid-complete': Use pre-built hybrid-complete bundle for faster dev (default)
   * - 'full': Use full bundle for complete compatibility
   * - 'auto': Generate minimal bundle even in dev
   */
  devFallback?: 'hybrid-complete' | 'full' | 'auto';

  /**
   * Global variable name for the hyperfixi API.
   * Defaults to 'hyperfixi'.
   */
  globalName?: string;

  /**
   * Bundle name for generated code comments.
   * Defaults to 'ViteAutoGenerated'.
   */
  bundleName?: string;

  /**
   * Enable verbose logging during development.
   */
  debug?: boolean;
}

/**
 * Usage information detected from a single file
 */
export interface FileUsage {
  /** Commands used in this file */
  commands: Set<string>;

  /** Block types used (if, repeat, for, while, fetch) */
  blocks: Set<string>;

  /** Whether positional expressions are used */
  positional: boolean;
}

/**
 * Aggregated usage information across all files
 */
export interface AggregatedUsage {
  /** All commands detected across all files */
  commands: Set<string>;

  /** All blocks detected across all files */
  blocks: Set<string>;

  /** Whether any file uses positional expressions */
  positional: boolean;

  /** Map of file paths to their usage */
  fileUsage: Map<string, FileUsage>;
}

/**
 * Information about a script that needs compilation
 */
export interface ScriptLocation {
  /** File path where the script was found */
  file: string;

  /** The hyperscript code */
  script: string;

  /** Line number in the file (for source maps) */
  line?: number;

  /** Column number in the file */
  column?: number;
}

/**
 * Aggregated scripts for compilation mode
 */
export interface AggregatedScripts {
  /** All unique scripts found across all files */
  scripts: Map<string, ScriptLocation[]>;

  /** Map of file paths to scripts in that file */
  fileScripts: Map<string, string[]>;
}
