// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: ar
// Re-generate after editing packages/semantic/src/generators/profiles/arabic.ts
// or packages/i18n/src/dictionaries/ar.ts.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "ar" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('ar', {
    hyperfixi: {
      attrs: {
        "hx-احصل": "hx-get",
        "hx-ضع": "hx-put",
        "hx-الهدف": "hx-target",
        "hx-استبدل": "hx-swap",
        "hx-تشغيل": "hx-trigger",
        "hx-على": "hx-on",
        "hx-مباشر": "hx-live",
        "sse-اتصل": "sse-connect",
        "sse-استبدل": "sse-swap",
        "ws-اتصل": "ws-connect",
        "ws-أرسل": "ws-send"
      },
      events: {
        "نقر": "click",
        "نقر مزدوج": "dblclick",
        "فأرة أسفل": "mousedown",
        "فأرة أعلى": "mouseup",
        "فأرة دخول": "mouseenter",
        "فأرة خروج": "mouseleave",
        "فأرة فوق": "mouseover",
        "فأرة خارج": "mouseout",
        "فأرة تحرك": "mousemove",
        "مفتاح أسفل": "keydown",
        "مفتاح أعلى": "keyup",
        "مفتاح ضغط": "keypress",
        "تركيز": "focus",
        "ضبابية": "blur",
        "تغيير": "change",
        "إدخال": "input",
        "إرسال": "submit",
        "إعادة تعيين": "reset",
        "تحميل": "load",
        "إلغاء تحميل": "unload",
        "تغيير حجم": "resize",
        "تمرير": "scroll",
        "بداية لمس": "touchstart",
        "نهاية لمس": "touchend",
        "تحرك لمس": "touchmove",
        "إلغاء لمس": "touchcancel"
      },
    },
  });
})();
