// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: ar
// Re-generate after editing packages/core/scripts/htmx-attr-vocab.mjs,
// packages/semantic/src/generators/profiles/arabic.ts
// or packages/i18n/src/dictionaries/ar.ts.
// Several names may map to one canonical: the first is the primary (the form
// to teach), later ones are aliases kept so already-authored pages still work.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "ar" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('ar', {
    hyperfixi: {
      attrs: {
        "hx-احصل": "hx-get",
        "hx-انشر": "hx-post",
        "hx-ضع": "hx-put",
        "hx-احذف": "hx-delete",
        "hx-الهدف": "hx-target",
        "hx-تبديل": "hx-swap",
        "hx-استبدل": "hx-swap",
        "hx-محفز": "hx-trigger",
        "hx-تشغيل": "hx-trigger",
        "hx-تأكيد": "hx-confirm",
        "hx-تعزيز": "hx-boost",
        "hx-قيم": "hx-vals",
        "hx-ادفع-url": "hx-push-url",
        "hx-على": "hx-on",
        "hx-مباشر": "hx-live",
        "hx-مؤشر": "hx-indicator",
        "hx-تضمين": "hx-include",
        "hx-اختيار": "hx-select",
        "hx-تبديل-oob": "hx-swap-oob",
        "hx-مزامنة": "hx-sync",
        "sse-اتصل": "sse-connect",
        "sse-تبديل": "sse-swap",
        "sse-استبدل": "sse-swap",
        "ws-اتصل": "ws-connect",
        "ws-أرسل": "ws-send"
      },
      events: {
        "بحث": "search",
        "مفتاح-أعلى": "keyup",
        "دخول-الفأرة": "mouseenter",
        "نقر": "click",
        "تركيز": "focus",
        "ضبابية": "blur",
        "تغيير": "change",
        "إدخال": "input",
        "إرسال": "submit",
        "تحميل": "load",
        "تمرير": "scroll"
      },
    },
  });
})();
