// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: bn
// Re-generate after editing packages/semantic/src/generators/profiles/bengali.ts
// or packages/i18n/src/dictionaries/bn.ts.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "bn" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('bn', {
    hyperfixi: {
      attrs: {
        "hx-পান": "hx-get",
        "hx-রাখুন": "hx-put",
        "hx-লক্ষ্য": "hx-target",
        "hx-বদল": "hx-swap",
        "hx-ট্রিগার": "hx-trigger",
        "hx-তে": "hx-on",
        "hx-লাইভ": "hx-live",
        "sse-কানেক্ট": "sse-connect",
        "sse-বদল": "sse-swap",
        "ws-কানেক্ট": "ws-connect",
        "ws-পাঠান": "ws-send"
      },
      events: {
        "ক্লিক": "click",
        "পরিবর্তন": "change",
        "ইনপুট": "input",
        "জমা": "submit",
        "লোড": "load",
        "ফোকাস": "focus",
        "ঝাপসা": "blur",
        "রিসেট": "reset",
        "কি-ডাউন": "keydown",
        "কি-আপ": "keyup",
        "মাউস-ওভার": "mouseover",
        "মাউস-আউট": "mouseout",
        "স্ক্রোল": "scroll",
        "রিসাইজ": "resize",
        "প্রতি": "every"
      },
    },
  });
})();
