// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: bn
// Re-generate after editing packages/core/scripts/htmx-attr-vocab.mjs,
// packages/semantic/src/generators/profiles/bengali.ts
// or packages/i18n/src/dictionaries/bn.ts.
// Several names may map to one canonical: the first is the primary (the form
// to teach), later ones are aliases kept so already-authored pages still work.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "bn" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('bn', {
    hyperfixi: {
      attrs: {
        "hx-পান": "hx-get",
        "hx-পোস্ট": "hx-post",
        "hx-রাখুন": "hx-put",
        "hx-মুছুন": "hx-delete",
        "hx-লক্ষ্য": "hx-target",
        "hx-বদল": "hx-swap",
        "hx-ট্রিগার": "hx-trigger",
        "hx-নিশ্চিত": "hx-confirm",
        "hx-বুস্ট": "hx-boost",
        "hx-মান": "hx-vals",
        "hx-পুশ-url": "hx-push-url",
        "hx-তে": "hx-on",
        "hx-লাইভ": "hx-live",
        "hx-সূচক": "hx-indicator",
        "hx-অন্তর্ভুক্ত": "hx-include",
        "hx-নির্বাচন": "hx-select",
        "hx-বদল-oob": "hx-swap-oob",
        "hx-সিঙ্ক": "hx-sync",
        "sse-কানেক্ট": "sse-connect",
        "sse-বদল": "sse-swap",
        "ws-কানেক্ট": "ws-connect",
        "ws-পাঠান": "ws-send"
      },
      events: {
        "খোঁজ": "search",
        "মাউস-প্রবেশ": "mouseenter",
        "ক্লিক": "click",
        "পরিবর্তন": "change",
        "ইনপুট": "input",
        "জমা": "submit",
        "লোড": "load",
        "ফোকাস": "focus",
        "ঝাপসা": "blur",
        "রিসেট": "reset",
        "স্ক্রোল": "scroll",
        "রিসাইজ": "resize",
        "প্রতি": "every",
        "কি-ডাউন": "keydown",
        "কি-আপ": "keyup",
        "মাউস-ওভার": "mouseover",
        "মাউস-আউট": "mouseout"
      },
    },
  });
})();
