// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: es
// Re-generate after editing packages/core/scripts/htmx-attr-vocab.mjs,
// packages/semantic/src/generators/profiles/spanish.ts
// or packages/i18n/src/dictionaries/es.ts.
// Several names may map to one canonical: the first is the primary (the form
// to teach), later ones are aliases kept so already-authored pages still work.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "es" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('es', {
    hyperfixi: {
      attrs: {
        "hx-obtener": "hx-get",
        "hx-publicar": "hx-post",
        "hx-poner": "hx-put",
        "hx-eliminar": "hx-delete",
        "hx-objetivo": "hx-target",
        "hx-intercambio": "hx-swap",
        "hx-intercambiar": "hx-swap",
        "hx-disparador": "hx-trigger",
        "hx-disparar": "hx-trigger",
        "hx-confirmar": "hx-confirm",
        "hx-impulsar": "hx-boost",
        "hx-empujar-url": "hx-push-url",
        "hx-en": "hx-on",
        "hx-en-vivo": "hx-live",
        "hx-indicador": "hx-indicator",
        "hx-incluir": "hx-include",
        "sse-conectar": "sse-connect",
        "sse-intercambio": "sse-swap",
        "sse-intercambiar": "sse-swap",
        "ws-conectar": "ws-connect",
        "ws-enviar": "ws-send"
      },
      events: {
        "clic": "click",
        "dobleclic": "dblclick",
        "ratónentrar": "mouseenter",
        "ratónsalir": "mouseleave",
        "ratónmover": "mousemove",
        "teclapresar": "keypress",
        "enfocar": "focus",
        "desenfocar": "blur",
        "cambiar": "change",
        "entrada": "input",
        "envío": "submit",
        "reiniciar": "reset",
        "cargar": "load",
        "descargar": "unload",
        "redimensionar": "resize",
        "desplazar": "scroll",
        "toqueempezar": "touchstart",
        "toqueterminar": "touchend",
        "toquemover": "touchmove",
        "toquecancelar": "touchcancel",
        "ratónabajo": "mousedown",
        "ratónarriba": "mouseup",
        "ratónencima": "mouseover",
        "ratónfuera": "mouseout",
        "teclaabajo": "keydown",
        "teclaarriba": "keyup",
        "enviar": "submit"
      },
    },
  });
})();
