// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: es
// Re-generate after editing packages/semantic/src/generators/profiles/spanish.ts
// or packages/i18n/src/dictionaries/es.ts.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "es" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('es', {
    hyperfixi: {
      attrs: {
        "hx-obtener": "hx-get",
        "hx-poner": "hx-put",
        "hx-objetivo": "hx-target",
        "hx-intercambiar": "hx-swap",
        "hx-disparar": "hx-trigger",
        "hx-en": "hx-on",
        "hx-en-vivo": "hx-live",
        "sse-conectar": "sse-connect",
        "sse-intercambiar": "sse-swap",
        "ws-conectar": "ws-connect",
        "ws-enviar": "ws-send"
      },
      events: {
        "clic": "click",
        "dobleclic": "dblclick",
        "ratónabajo": "mousedown",
        "ratónarriba": "mouseup",
        "ratónentrar": "mouseenter",
        "ratónsalir": "mouseleave",
        "ratónencima": "mouseover",
        "ratónfuera": "mouseout",
        "ratónmover": "mousemove",
        "teclaabajo": "keydown",
        "teclaarriba": "keyup",
        "teclapresar": "keypress",
        "enfocar": "focus",
        "desenfocar": "blur",
        "cambiar": "change",
        "entrada": "input",
        "enviar": "submit",
        "reiniciar": "reset",
        "cargar": "load",
        "descargar": "unload",
        "redimensionar": "resize",
        "desplazar": "scroll",
        "toqueempezar": "touchstart",
        "toqueterminar": "touchend",
        "toquemover": "touchmove",
        "toquecancelar": "touchcancel"
      },
    },
  });
})();
