// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: fr
// Re-generate after editing packages/semantic/src/generators/profiles/french.ts
// or packages/i18n/src/dictionaries/fr.ts.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "fr" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('fr', {
    hyperfixi: {
      attrs: {
        "hx-obtenir": "hx-get",
        "hx-mettre": "hx-put",
        "hx-cible": "hx-target",
        "hx-échanger": "hx-swap",
        "hx-déclencher": "hx-trigger",
        "hx-sur": "hx-on",
        "hx-en-direct": "hx-live",
        "sse-connecter": "sse-connect",
        "sse-échanger": "sse-swap",
        "ws-connecter": "ws-connect",
        "ws-envoyer": "ws-send"
      },
      events: {
        "clic": "click",
        "doubleclic": "dblclick",
        "sourisappuyée": "mousedown",
        "sourisrelâchée": "mouseup",
        "sourisentrer": "mouseenter",
        "sourissortir": "mouseleave",
        "sourissur": "mouseover",
        "sourisdehors": "mouseout",
        "sourisbouger": "mousemove",
        "toucheappuyée": "keydown",
        "toucherelâchée": "keyup",
        "touchepressée": "keypress",
        "flou": "blur",
        "changer": "change",
        "saisie": "input",
        "soumettre": "submit",
        "réinitialiser": "reset",
        "charger": "load",
        "décharger": "unload",
        "redimensionner": "resize",
        "défiler": "scroll",
        "touchercommencer": "touchstart",
        "toucherfin": "touchend",
        "toucherbouger": "touchmove",
        "toucherannuler": "touchcancel"
      },
    },
  });
})();
