// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: he
// Re-generate after editing packages/core/scripts/htmx-attr-vocab.mjs,
// packages/semantic/src/generators/profiles/hebrew.ts
// or packages/i18n/src/dictionaries/he.ts.
// Several names may map to one canonical: the first is the primary (the form
// to teach), later ones are aliases kept so already-authored pages still work.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "he" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('he', {
    hyperfixi: {
      attrs: {
        "hx-קבל": "hx-get",
        "hx-פרסם": "hx-post",
        "hx-שים": "hx-put",
        "hx-מחק": "hx-delete",
        "hx-יעד": "hx-target",
        "hx-החלפה": "hx-swap",
        "hx-החלף": "hx-swap",
        "hx-מפעיל": "hx-trigger",
        "hx-הפעל": "hx-trigger",
        "hx-אישור": "hx-confirm",
        "hx-האצה": "hx-boost",
        "hx-ערכים": "hx-vals",
        "hx-דחוף-url": "hx-push-url",
        "hx-ב": "hx-on",
        "hx-חי": "hx-live",
        "hx-מחוון": "hx-indicator",
        "hx-כלול": "hx-include",
        "hx-בחירה": "hx-select",
        "hx-החלפה-oob": "hx-swap-oob",
        "hx-סנכרון": "hx-sync",
        "sse-התחבר": "sse-connect",
        "sse-החלפה": "sse-swap",
        "sse-החלף": "sse-swap",
        "ws-התחבר": "ws-connect",
        "ws-שלח": "ws-send"
      },
      events: {
        "חיפוש": "search",
        "שחרור-מקש": "keyup",
        "טעינה": "load",
        "כניסת-עכבר": "mouseenter",
        "טשטש": "blur",
        "שינוי": "change",
        "לחיצה": "click",
        "מקד": "focus",
        "קלט": "input",
        "שליחה": "submit"
      },
    },
  });
})();
