// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: he
// Re-generate after editing packages/semantic/src/generators/profiles/hebrew.ts
// or packages/i18n/src/dictionaries/he.ts.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "he" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('he', {
    hyperfixi: {
      attrs: {
        "hx-קבל": "hx-get",
        "hx-שים": "hx-put",
        "hx-יעד": "hx-target",
        "hx-החלף": "hx-swap",
        "hx-הפעל": "hx-trigger",
        "hx-ב": "hx-on",
        "hx-חי": "hx-live",
        "sse-התחבר": "sse-connect",
        "sse-החלף": "sse-swap",
        "ws-התחבר": "ws-connect",
        "ws-שלח": "ws-send"
      },
      events: {
        "טשטש": "blur",
        "שינוי": "change",
        "לחיצה": "click",
        "מקד": "focus",
        "קלט": "input",
        "שליחה": "submit"
      },
    },
  });
})();
