// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: hi
// Re-generate after editing packages/semantic/src/generators/profiles/hindi.ts
// or packages/i18n/src/dictionaries/hi.ts.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "hi" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('hi', {
    hyperfixi: {
      attrs: {
        "hx-प्राप्त": "hx-get",
        "hx-रखें": "hx-put",
        "hx-लक्ष्य": "hx-target",
        "hx-बदलें_स्थान": "hx-swap",
        "hx-ट्रिगर": "hx-trigger",
        "hx-पर": "hx-on",
        "hx-लाइव": "hx-live",
        "sse-कनेक्ट": "sse-connect",
        "sse-बदलें_स्थान": "sse-swap",
        "ws-कनेक्ट": "ws-connect",
        "ws-भेजें": "ws-send"
      },
      events: {
        "क्लिक": "click",
        "डबल_क्लिक": "dblclick",
        "माउस_नीचे": "mousedown",
        "माउस_ऊपर": "mouseup",
        "माउस_प्रवेश": "mouseenter",
        "माउस_बाहर": "mouseleave",
        "माउस_ओवर": "mouseover",
        "माउस_आउट": "mouseout",
        "माउस_मूव": "mousemove",
        "की_नीचे": "keydown",
        "की_ऊपर": "keyup",
        "की_प्रेस": "keypress",
        "फोकस": "focus",
        "धुंधला": "blur",
        "परिवर्तन": "change",
        "इनपुट": "input",
        "जमा": "submit",
        "रीसेट": "reset",
        "लोड": "load",
        "अनलोड": "unload",
        "आकार_बदलें": "resize",
        "स्क्रॉल": "scroll",
        "टच_शुरू": "touchstart",
        "टच_समाप्त": "touchend",
        "टच_मूव": "touchmove",
        "टच_रद्द": "touchcancel"
      },
    },
  });
})();
