// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: hi
// Re-generate after editing packages/core/scripts/htmx-attr-vocab.mjs,
// packages/semantic/src/generators/profiles/hindi.ts
// or packages/i18n/src/dictionaries/hi.ts.
// Several names may map to one canonical: the first is the primary (the form
// to teach), later ones are aliases kept so already-authored pages still work.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "hi" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('hi', {
    hyperfixi: {
      attrs: {
        "hx-प्राप्त": "hx-get",
        "hx-पोस्ट": "hx-post",
        "hx-रखें": "hx-put",
        "hx-हटाएं": "hx-delete",
        "hx-लक्ष्य": "hx-target",
        "hx-अदला-बदली": "hx-swap",
        "hx-विनिमय": "hx-swap",
        "hx-ट्रिगर": "hx-trigger",
        "hx-पुष्टि": "hx-confirm",
        "hx-बूस्ट": "hx-boost",
        "hx-मान": "hx-vals",
        "hx-पुश-url": "hx-push-url",
        "hx-पर": "hx-on",
        "hx-लाइव": "hx-live",
        "hx-संकेतक": "hx-indicator",
        "hx-शामिल": "hx-include",
        "hx-चयन": "hx-select",
        "hx-अदला-बदली-oob": "hx-swap-oob",
        "hx-सिंक": "hx-sync",
        "sse-कनेक्ट": "sse-connect",
        "sse-अदला-बदली": "sse-swap",
        "sse-विनिमय": "sse-swap",
        "ws-कनेक्ट": "ws-connect",
        "ws-भेजें": "ws-send",
        "hx-बदलें_स्थान": "hx-swap",
        "sse-बदलें_स्थान": "sse-swap"
      },
      events: {
        "खोज": "search",
        "क्लिक": "click",
        "डबल_क्लिक": "dblclick",
        "माउसनीचे": "mousedown",
        "माउसऊपर": "mouseup",
        "माउस_प्रवेश": "mouseenter",
        "माउस_बाहर": "mouseleave",
        "माउस_ओवर": "mouseover",
        "माउस_आउट": "mouseout",
        "माउस_मूव": "mousemove",
        "की_नीचे": "keydown",
        "की_ऊपर": "keyup",
        "की_प्रेस": "keypress",
        "फोकस": "focus",
        "धुंधला": "blur",
        "परिवर्तन": "change",
        "इनपुट": "input",
        "जमा": "submit",
        "रीसेट": "reset",
        "लोड": "load",
        "अनलोड": "unload",
        "आकार_बदलें": "resize",
        "स्क्रॉल": "scroll",
        "टच_शुरू": "touchstart",
        "टच_समाप्त": "touchend",
        "टच_मूव": "touchmove",
        "टच_रद्द": "touchcancel",
        "माउस_नीचे": "mousedown",
        "माउस_ऊपर": "mouseup"
      },
    },
  });
})();
