// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: id
// Re-generate after editing packages/core/scripts/htmx-attr-vocab.mjs,
// packages/semantic/src/generators/profiles/indonesian.ts
// or packages/i18n/src/dictionaries/id.ts.
// Several names may map to one canonical: the first is the primary (the form
// to teach), later ones are aliases kept so already-authored pages still work.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "id" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('id', {
    hyperfixi: {
      attrs: {
        "hx-dapatkan": "hx-get",
        "hx-taruh": "hx-put",
        "hx-tukar": "hx-swap",
        "hx-picu": "hx-trigger",
        "hx-pada": "hx-on",
        "hx-langsung": "hx-live",
        "sse-sambungkan": "sse-connect",
        "sse-tukar": "sse-swap",
        "ws-sambungkan": "ws-connect",
        "ws-kirim": "ws-send"
      },
      events: {
        "klik": "click",
        "arahkan": "mouseover",
        "tinggalkan": "mouseout",
        "tekan_tombol": "keydown",
        "fokus": "focus",
        "ubah": "change",
        "masukan": "input",
        "kirim": "submit",
        "muat": "load",
        "bongkar": "unload",
        "ubah_ukuran": "resize",
        "gulir": "scroll",
        "klik_ganda": "dblclick",
        "tekan_mouse": "mousedown",
        "lepas_mouse": "mouseup",
        "mouse_masuk": "mouseenter",
        "mouse_keluar": "mouseleave",
        "mouse_atas": "mouseover",
        "mouse_luar": "mouseout",
        "gerak_mouse": "mousemove",
        "lepas_tombol": "keyup",
        "pencet_tombol": "keypress",
        "mulai_sentuh": "touchstart",
        "akhir_sentuh": "touchend",
        "gerak_sentuh": "touchmove",
        "batal_sentuh": "touchcancel"
      },
    },
  });
})();
