// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: it
// Re-generate after editing packages/semantic/src/generators/profiles/italian.ts
// or packages/i18n/src/dictionaries/it.ts.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "it" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('it', {
    hyperfixi: {
      attrs: {
        "hx-ottenere": "hx-get",
        "hx-mettere": "hx-put",
        "hx-obiettivo": "hx-target",
        "hx-scambiare": "hx-swap",
        "hx-scatenare": "hx-trigger",
        "hx-su": "hx-on",
        "hx-in-diretta": "hx-live",
        "sse-connettere": "sse-connect",
        "sse-scambiare": "sse-swap",
        "ws-connettere": "ws-connect",
        "ws-inviare": "ws-send"
      },
      events: {
        "clic": "click",
        "doppioclic": "dblclick",
        "mousegiù": "mousedown",
        "mousesu": "mouseup",
        "mouseentra": "mouseenter",
        "mouseesce": "mouseleave",
        "mousesopra": "mouseover",
        "mousefuori": "mouseout",
        "mousemuovi": "mousemove",
        "tastogiù": "keydown",
        "tastosu": "keyup",
        "tastopremi": "keypress",
        "fuoco": "focus",
        "sfuocatura": "blur",
        "cambio": "change",
        "invio": "submit",
        "carica": "load",
        "scarica": "unload",
        "ridimensiona": "resize",
        "scorrimento": "scroll",
        "toccoinizia": "touchstart",
        "toccofine": "touchend",
        "toccomuovi": "touchmove",
        "toccoannulla": "touchcancel"
      },
    },
  });
})();
