// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: it
// Re-generate after editing packages/core/scripts/htmx-attr-vocab.mjs,
// packages/semantic/src/generators/profiles/italian.ts
// or packages/i18n/src/dictionaries/it.ts.
// Several names may map to one canonical: the first is the primary (the form
// to teach), later ones are aliases kept so already-authored pages still work.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "it" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('it', {
    hyperfixi: {
      attrs: {
        "hx-ottenere": "hx-get",
        "hx-pubblicare": "hx-post",
        "hx-mettere": "hx-put",
        "hx-eliminare": "hx-delete",
        "hx-obiettivo": "hx-target",
        "hx-destinazione": "hx-target",
        "hx-scambio": "hx-swap",
        "hx-scambiare": "hx-swap",
        "hx-attivatore": "hx-trigger",
        "hx-scatenare": "hx-trigger",
        "hx-confermare": "hx-confirm",
        "hx-potenziare": "hx-boost",
        "hx-valori": "hx-vals",
        "hx-spingere-url": "hx-push-url",
        "hx-su": "hx-on",
        "hx-in-diretta": "hx-live",
        "hx-indicatore": "hx-indicator",
        "hx-includere": "hx-include",
        "hx-selezione": "hx-select",
        "hx-scambio-oob": "hx-swap-oob",
        "hx-sincronizzazione": "hx-sync",
        "sse-connettere": "sse-connect",
        "sse-scambio": "sse-swap",
        "sse-scambiare": "sse-swap",
        "ws-connettere": "ws-connect",
        "ws-inviare": "ws-send"
      },
      events: {
        "cercare": "search",
        "clic": "click",
        "doppioclic": "dblclick",
        "mouseentra": "mouseenter",
        "mouseesce": "mouseleave",
        "mousesopra": "mouseover",
        "mousefuori": "mouseout",
        "mousemuovi": "mousemove",
        "tastogiù": "keydown",
        "tastosu": "keyup",
        "tastopremi": "keypress",
        "fuoco": "focus",
        "sfuocare": "blur",
        "cambio": "change",
        "invio": "submit",
        "reimpostare": "reset",
        "carica": "load",
        "scarica": "unload",
        "ridimensiona": "resize",
        "scorrimento": "scroll",
        "toccoinizia": "touchstart",
        "toccofine": "touchend",
        "toccomuovi": "touchmove",
        "toccoannulla": "touchcancel",
        "mousegiù": "mousedown",
        "mousesu": "mouseup",
        "sfuocatura": "blur"
      },
    },
  });
})();
