// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: ja
// Re-generate after editing packages/semantic/src/generators/profiles/japanese.ts
// or packages/i18n/src/dictionaries/ja.ts.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "ja" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('ja', {
    hyperfixi: {
      attrs: {
        "hx-取得": "hx-get",
        "hx-置く": "hx-put",
        "hx-ターゲット": "hx-target",
        "hx-交換": "hx-swap",
        "hx-引き金": "hx-trigger",
        "hx-で": "hx-on",
        "hx-ライブ": "hx-live",
        "sse-接続": "sse-connect",
        "sse-交換": "sse-swap",
        "ws-接続": "ws-connect",
        "ws-送る": "ws-send"
      },
      events: {
        "クリック": "click",
        "ダブルクリック": "dblclick",
        "マウス押下": "mousedown",
        "マウス解放": "mouseup",
        "マウス入る": "mouseenter",
        "マウス離れる": "mouseleave",
        "マウス上": "mouseover",
        "マウス外": "mouseout",
        "マウス移動": "mousemove",
        "キー押下": "keydown",
        "キー解放": "keyup",
        "キー押す": "keypress",
        "フォーカス": "focus",
        "ぼかし": "blur",
        "変更": "change",
        "入力": "input",
        "送信": "submit",
        "リセット": "reset",
        "読み込み": "load",
        "読み込み解除": "unload",
        "サイズ変更": "resize",
        "スクロール": "scroll",
        "タッチ開始": "touchstart",
        "タッチ終了": "touchend",
        "タッチ移動": "touchmove",
        "タッチキャンセル": "touchcancel"
      },
    },
  });
})();
