// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: ko
// Re-generate after editing packages/core/scripts/htmx-attr-vocab.mjs,
// packages/semantic/src/generators/profiles/korean.ts
// or packages/i18n/src/dictionaries/ko.ts.
// Several names may map to one canonical: the first is the primary (the form
// to teach), later ones are aliases kept so already-authored pages still work.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "ko" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('ko', {
    hyperfixi: {
      attrs: {
        "hx-얻다": "hx-get",
        "hx-게시": "hx-post",
        "hx-넣다": "hx-put",
        "hx-삭제": "hx-delete",
        "hx-대상": "hx-target",
        "hx-타겟": "hx-target",
        "hx-교체": "hx-swap",
        "hx-스왑": "hx-swap",
        "hx-교환": "hx-swap",
        "hx-트리거": "hx-trigger",
        "hx-확인": "hx-confirm",
        "hx-부스트": "hx-boost",
        "hx-푸시-url": "hx-push-url",
        "hx-에": "hx-on",
        "hx-실시간": "hx-live",
        "hx-인디케이터": "hx-indicator",
        "hx-포함": "hx-include",
        "sse-연결": "sse-connect",
        "sse-교체": "sse-swap",
        "sse-스왑": "sse-swap",
        "sse-교환": "sse-swap",
        "ws-연결": "ws-connect",
        "ws-보내다": "ws-send"
      },
      events: {
        "검색": "search",
        "클릭": "click",
        "더블클릭": "dblclick",
        "마우스다운": "mousedown",
        "마우스업": "mouseup",
        "마우스엔터": "mouseenter",
        "마우스리브": "mouseleave",
        "마우스오버": "mouseover",
        "마우스아웃": "mouseout",
        "마우스무브": "mousemove",
        "키다운": "keydown",
        "키업": "keyup",
        "키프레스": "keypress",
        "포커스": "focus",
        "블러": "blur",
        "변경": "change",
        "입력": "input",
        "제출": "submit",
        "재설정": "reset",
        "로드": "load",
        "리사이즈": "resize",
        "스크롤": "scroll",
        "터치종료": "touchend",
        "터치취소": "touchcancel",
        "리셋": "reset",
        "언로드": "unload",
        "터치시작": "touchstart",
        "터치이동": "touchmove"
      },
    },
  });
})();
