// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: ms
// Re-generate after editing packages/core/scripts/htmx-attr-vocab.mjs,
// packages/semantic/src/generators/profiles/malay.ts
// or packages/i18n/src/dictionaries/ms.ts.
// Several names may map to one canonical: the first is the primary (the form
// to teach), later ones are aliases kept so already-authored pages still work.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "ms" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('ms', {
    hyperfixi: {
      attrs: {
        "hx-dapatkan": "hx-get",
        "hx-hantar": "hx-post",
        "hx-letak": "hx-put",
        "hx-padam": "hx-delete",
        "hx-sasaran": "hx-target",
        "hx-tukar": "hx-swap",
        "hx-tukar_tempat": "hx-swap",
        "hx-pencetus": "hx-trigger",
        "hx-cetuskan": "hx-trigger",
        "hx-sahkan": "hx-confirm",
        "hx-percepat": "hx-boost",
        "hx-nilai": "hx-vals",
        "hx-tolak-url": "hx-push-url",
        "hx-apabila": "hx-on",
        "hx-langsung": "hx-live",
        "hx-penunjuk": "hx-indicator",
        "hx-sertakan": "hx-include",
        "hx-pilihan": "hx-select",
        "hx-tukar-oob": "hx-swap-oob",
        "hx-segerak": "hx-sync",
        "sse-sambung": "sse-connect",
        "sse-tukar": "sse-swap",
        "sse-tukar_tempat": "sse-swap",
        "ws-sambung": "ws-connect",
        "ws-hantar": "ws-send"
      },
      events: {
        "klik": "click",
        "lepas-kekunci": "keyup",
        "ubah": "change",
        "muat": "load",
        "tetikus-masuk": "mouseenter",
        "cari": "search",
        "setiap": "every"
      },
    },
  });
})();
