// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: ms
// Re-generate after editing packages/semantic/src/generators/profiles/malay.ts
// or packages/i18n/src/dictionaries/ms.ts.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "ms" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('ms', {
    hyperfixi: {
      attrs: {
        "hx-dapatkan": "hx-get",
        "hx-letak": "hx-put",
        "hx-sasaran": "hx-target",
        "hx-tukar_tempat": "hx-swap",
        "hx-cetuskan": "hx-trigger",
        "hx-apabila": "hx-on",
        "hx-langsung": "hx-live",
        "sse-sambung": "sse-connect",
        "sse-tukar_tempat": "sse-swap",
        "ws-sambung": "ws-connect",
        "ws-hantar": "ws-send"
      },
      events: {
        "setiap": "every"
      },
    },
  });
})();
