// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: pl
// Re-generate after editing packages/semantic/src/generators/profiles/polish.ts
// or packages/i18n/src/dictionaries/pl.ts.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "pl" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('pl', {
    hyperfixi: {
      attrs: {
        "hx-uzyskaj": "hx-get",
        "hx-umieść": "hx-put",
        "hx-cel": "hx-target",
        "hx-zamień": "hx-swap",
        "hx-wyzwól": "hx-trigger",
        "hx-gdy": "hx-on",
        "hx-na-żywo": "hx-live",
        "sse-połącz": "sse-connect",
        "sse-zamień": "sse-swap",
        "ws-połącz": "ws-connect",
        "ws-wyślij": "ws-send"
      },
      events: {
        "kliknięcie": "click",
        "podwójnekliknięcie": "dblclick",
        "myszdół": "mousedown",
        "myszgóra": "mouseup",
        "myszwejście": "mouseenter",
        "myszwyjście": "mouseleave",
        "mysznad": "mouseover",
        "myszpoza": "mouseout",
        "myszruch": "mousemove",
        "klawiszdół": "keydown",
        "klawiszgóra": "keyup",
        "klawisznaciśnięcie": "keypress",
        "fokus": "focus",
        "rozmycie": "blur",
        "zmiana": "change",
        "wejście": "input",
        "wyślij": "submit",
        "resetuj": "reset",
        "załaduj": "load",
        "wyładuj": "unload",
        "zmieńrozmiar": "resize",
        "przewiń": "scroll",
        "dotykstart": "touchstart",
        "dotykkoniec": "touchend",
        "dotykruch": "touchmove",
        "dotykanuluj": "touchcancel"
      },
    },
  });
})();
