// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: pt
// Re-generate after editing packages/core/scripts/htmx-attr-vocab.mjs,
// packages/semantic/src/generators/profiles/portuguese.ts
// or packages/i18n/src/dictionaries/pt.ts.
// Several names may map to one canonical: the first is the primary (the form
// to teach), later ones are aliases kept so already-authored pages still work.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "pt" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('pt', {
    hyperfixi: {
      attrs: {
        "hx-obter": "hx-get",
        "hx-publicar": "hx-post",
        "hx-colocar": "hx-put",
        "hx-excluir": "hx-delete",
        "hx-eliminar": "hx-delete",
        "hx-alvo": "hx-target",
        "hx-destino": "hx-target",
        "hx-troca": "hx-swap",
        "hx-trocar": "hx-swap",
        "hx-gatilho": "hx-trigger",
        "hx-disparar": "hx-trigger",
        "hx-confirmar": "hx-confirm",
        "hx-impulsionar": "hx-boost",
        "hx-valores": "hx-vals",
        "hx-empurrar-url": "hx-push-url",
        "hx-em": "hx-on",
        "hx-ao-vivo": "hx-live",
        "hx-indicador": "hx-indicator",
        "hx-incluir": "hx-include",
        "hx-seleção": "hx-select",
        "hx-troca-oob": "hx-swap-oob",
        "hx-sincronização": "hx-sync",
        "sse-conectar": "sse-connect",
        "sse-troca": "sse-swap",
        "sse-trocar": "sse-swap",
        "ws-conectar": "ws-connect",
        "ws-enviar": "ws-send"
      },
      events: {
        "buscar": "search",
        "clique": "click",
        "duploClique": "dblclick",
        "mouseEntrar": "mouseenter",
        "mouseSair": "mouseleave",
        "mouseMover": "mousemove",
        "teclaPressionar": "keypress",
        "foco": "focus",
        "desfoque": "blur",
        "mudança": "change",
        "entrada": "input",
        "envio": "submit",
        "redefinir": "reset",
        "carregar": "load",
        "descarregar": "unload",
        "redimensionar": "resize",
        "rolar": "scroll",
        "toqueInício": "touchstart",
        "toqueFim": "touchend",
        "toqueMover": "touchmove",
        "toqueCancelar": "touchcancel",
        "mouseBaixo": "mousedown",
        "mouseCima": "mouseup",
        "mouseSobre": "mouseover",
        "mouseFora": "mouseout",
        "teclaBaixo": "keydown",
        "teclaCima": "keyup",
        "reiniciar": "reset"
      },
    },
  });
})();
