// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: pt
// Re-generate after editing packages/semantic/src/generators/profiles/portuguese.ts
// or packages/i18n/src/dictionaries/pt.ts.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "pt" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('pt', {
    hyperfixi: {
      attrs: {
        "hx-obter": "hx-get",
        "hx-colocar": "hx-put",
        "hx-alvo": "hx-target",
        "hx-trocar": "hx-swap",
        "hx-disparar": "hx-trigger",
        "hx-em": "hx-on",
        "hx-ao-vivo": "hx-live",
        "sse-conectar": "sse-connect",
        "sse-trocar": "sse-swap",
        "ws-conectar": "ws-connect",
        "ws-enviar": "ws-send"
      },
      events: {
        "clique": "click",
        "duploClique": "dblclick",
        "mouseBaixo": "mousedown",
        "mouseCima": "mouseup",
        "mouseEntrar": "mouseenter",
        "mouseSair": "mouseleave",
        "mouseSobre": "mouseover",
        "mouseFora": "mouseout",
        "mouseMover": "mousemove",
        "teclaBaixo": "keydown",
        "teclaCima": "keyup",
        "teclaPressionar": "keypress",
        "foco": "focus",
        "desfoque": "blur",
        "mudança": "change",
        "entrada": "input",
        "envio": "submit",
        "reiniciar": "reset",
        "carregar": "load",
        "descarregar": "unload",
        "redimensionar": "resize",
        "rolar": "scroll",
        "toqueInício": "touchstart",
        "toqueFim": "touchend",
        "toqueMover": "touchmove",
        "toqueCancelar": "touchcancel"
      },
    },
  });
})();
