// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: qu
// Re-generate after editing packages/semantic/src/generators/profiles/quechua.ts
// or packages/i18n/src/dictionaries/qu.ts.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "qu" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('qu', {
    hyperfixi: {
      attrs: {
        "hx-taripay": "hx-get",
        "hx-churay": "hx-put",
        "hx-ñawpaqman": "hx-target",
        "hx-t'inkuy": "hx-swap",
        "hx-kuyuchiy": "hx-trigger",
        "hx-chaypim": "hx-on",
        "hx-kawsachkaq": "hx-live",
        "sse-tinkiy": "sse-connect",
        "sse-t'inkuy": "sse-swap",
        "ws-tinkiy": "ws-connect",
        "ws-kachay": "ws-send"
      },
      events: {
        "ñitiy": "click",
        "iskay_ñitiy": "dblclick",
        "rat_ñitiy": "mousedown",
        "rat_huqariy": "mouseup",
        "rat_yaykuy": "mouseenter",
        "rat_lluqsiy": "mouseleave",
        "rat_hawapi": "mouseover",
        "rat_hawamanta": "mouseout",
        "rat_kuyuy": "mousemove",
        "yupana_ñitiy": "keydown",
        "yupana_huqariy": "keyup",
        "yupana_ñitana": "keypress",
        "qhaway": "focus",
        "paqariy": "blur",
        "tikray": "change",
        "yaykuchiy": "input",
        "kachay": "submit",
        "qallariy": "reset",
        "apakuy": "load",
        "urmay": "unload",
        "hatun_kay": "resize",
        "kunray": "scroll",
        "llamiy_qallay": "touchstart",
        "llamiy_tukuy": "touchend",
        "llamiy_kuyuy": "touchmove",
        "llamiy_hark_ay": "touchcancel"
      },
    },
  });
})();
