// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: qu
// Re-generate after editing packages/core/scripts/htmx-attr-vocab.mjs,
// packages/semantic/src/generators/profiles/quechua.ts
// or packages/i18n/src/dictionaries/qu.ts.
// Several names may map to one canonical: the first is the primary (the form
// to teach), later ones are aliases kept so already-authored pages still work.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "qu" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('qu', {
    hyperfixi: {
      attrs: {
        "hx-taripay": "hx-get",
        "hx-apachiy": "hx-post",
        "hx-churay": "hx-put",
        "hx-pichay": "hx-delete",
        "hx-punta": "hx-target",
        "hx-tikray": "hx-swap",
        "hx-t'inkuy": "hx-swap",
        "hx-kuyuchiy": "hx-trigger",
        "hx-takyachiy": "hx-confirm",
        "hx-utqhaychiy": "hx-boost",
        "hx-chanikuna": "hx-vals",
        "hx-tanqay-url": "hx-push-url",
        "hx-chaypim": "hx-on",
        "hx-kawsachkaq": "hx-live",
        "hx-rikuchiq": "hx-indicator",
        "hx-yapay": "hx-include",
        "hx-akllay": "hx-select",
        "hx-tikray-oob": "hx-swap-oob",
        "hx-kuskachay": "hx-sync",
        "sse-tinkiy": "sse-connect",
        "sse-tikray": "sse-swap",
        "sse-t'inkuy": "sse-swap",
        "ws-tinkiy": "ws-connect",
        "ws-kachay": "ws-send",
        "hx-ñawpaqman": "hx-target"
      },
      events: {
        "maskay": "search",
        "ñitiy": "click",
        "ratñitiy": "mousedown",
        "rathuqariy": "mouseup",
        "qhaway": "focus",
        "paqariy": "blur",
        "kambiay": "change",
        "yaykuchiy": "input",
        "apaykachay": "submit",
        "musuqchay": "reset",
        "apakuy": "load",
        "hatun_kay": "resize",
        "kunray": "scroll",
        "iskay_ñitiy": "dblclick",
        "rat_ñitiy": "mousedown",
        "rat_huqariy": "mouseup",
        "rat_yaykuy": "mouseenter",
        "rat_lluqsiy": "mouseleave",
        "rat_hawapi": "mouseover",
        "rat_hawamanta": "mouseout",
        "rat_kuyuy": "mousemove",
        "yupana_ñitiy": "keydown",
        "yupana_huqariy": "keyup",
        "yupana_ñitana": "keypress",
        "tikray": "change",
        "kachay": "submit",
        "qallariy": "reset",
        "urmay": "unload",
        "llamiy_qallay": "touchstart",
        "llamiy_tukuy": "touchend",
        "llamiy_kuyuy": "touchmove",
        "llamiy_hark_ay": "touchcancel"
      },
    },
  });
})();
