// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: ru
// Re-generate after editing packages/core/scripts/htmx-attr-vocab.mjs,
// packages/semantic/src/generators/profiles/russian.ts
// or packages/i18n/src/dictionaries/ru.ts.
// Several names may map to one canonical: the first is the primary (the form
// to teach), later ones are aliases kept so already-authored pages still work.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "ru" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('ru', {
    hyperfixi: {
      attrs: {
        "hx-получить": "hx-get",
        "hx-положить": "hx-put",
        "hx-цель": "hx-target",
        "hx-поменять": "hx-swap",
        "hx-инициировать": "hx-trigger",
        "hx-при": "hx-on",
        "hx-в-прямом-эфире": "hx-live",
        "sse-подключить": "sse-connect",
        "sse-поменять": "sse-swap",
        "ws-подключить": "ws-connect",
        "ws-отправить": "ws-send"
      },
      events: {
        "клик": "click",
        "двойной_клик": "dblclick",
        "мышьвниз": "mousedown",
        "мышьвверх": "mouseup",
        "мышь_вход": "mouseenter",
        "мышь_выход": "mouseleave",
        "наведение": "mouseover",
        "уход": "mouseout",
        "движение_мыши": "mousemove",
        "клавиша_вниз": "keydown",
        "клавиша_вверх": "keyup",
        "нажатие_клавиши": "keypress",
        "фокус": "focus",
        "потеря_фокуса": "blur",
        "изменение": "change",
        "ввод": "input",
        "отправка": "submit",
        "сбросить": "reset",
        "загрузка": "load",
        "выгрузка": "unload",
        "изменениеразмера": "resize",
        "прокрутка": "scroll",
        "касание_начало": "touchstart",
        "касание_конец": "touchend",
        "касание_движение": "touchmove",
        "касание_отмена": "touchcancel",
        "мышь_вниз": "mousedown",
        "мышь_вверх": "mouseup",
        "сброс": "reset",
        "изменение_размера": "resize"
      },
    },
  });
})();
