// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: sw
// Re-generate after editing packages/semantic/src/generators/profiles/swahili.ts
// or packages/i18n/src/dictionaries/sw.ts.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "sw" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('sw', {
    hyperfixi: {
      attrs: {
        "hx-pata": "hx-get",
        "hx-weka": "hx-put",
        "hx-lengo": "hx-target",
        "hx-badilishana": "hx-swap",
        "hx-chochea": "hx-trigger",
        "hx-unapo": "hx-on",
        "hx-moja-kwa-moja": "hx-live",
        "sse-unganisha": "sse-connect",
        "sse-badilishana": "sse-swap",
        "ws-unganisha": "ws-connect",
        "ws-tuma": "ws-send"
      },
      events: {
        "bonyeza": "click",
        "bonyeza_mara_mbili": "dblclick",
        "panya_shuka": "mousedown",
        "panya_juu": "mouseover",
        "panya_ingia": "mouseenter",
        "panya_toka": "mouseleave",
        "panya_nje": "mouseout",
        "panya_sogea": "mousemove",
        "kitufe_shuka": "keydown",
        "kitufe_juu": "keyup",
        "kitufe_bonyeza": "keypress",
        "zingatia": "focus",
        "poteza_macho": "blur",
        "badilisha": "change",
        "ingizo": "input",
        "wasilisha": "submit",
        "weka_upya": "reset",
        "pakia": "load",
        "shuka": "unload",
        "badilisha_ukubwa": "resize",
        "sogeza": "scroll",
        "gusa_anza": "touchstart",
        "gusa_mwisho": "touchend",
        "gusa_sogea": "touchmove",
        "gusa_ghairi": "touchcancel"
      },
    },
  });
})();
