// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: sw
// Re-generate after editing packages/core/scripts/htmx-attr-vocab.mjs,
// packages/semantic/src/generators/profiles/swahili.ts
// or packages/i18n/src/dictionaries/sw.ts.
// Several names may map to one canonical: the first is the primary (the form
// to teach), later ones are aliases kept so already-authored pages still work.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "sw" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('sw', {
    hyperfixi: {
      attrs: {
        "hx-pata": "hx-get",
        "hx-chapisha": "hx-post",
        "hx-weka": "hx-put",
        "hx-futa": "hx-delete",
        "hx-lengo": "hx-target",
        "hx-badilisha": "hx-swap",
        "hx-badilishana": "hx-swap",
        "hx-kichocheo": "hx-trigger",
        "hx-chochea": "hx-trigger",
        "hx-thibitisha": "hx-confirm",
        "hx-harakisha": "hx-boost",
        "hx-thamani": "hx-vals",
        "hx-sukuma-url": "hx-push-url",
        "hx-unapo": "hx-on",
        "hx-moja-kwa-moja": "hx-live",
        "hx-kiashiria": "hx-indicator",
        "hx-jumuisha": "hx-include",
        "hx-uteuzi": "hx-select",
        "hx-badilisha-oob": "hx-swap-oob",
        "hx-sawazisha": "hx-sync",
        "sse-unganisha": "sse-connect",
        "sse-badilisha": "sse-swap",
        "sse-badilishana": "sse-swap",
        "ws-unganisha": "ws-connect",
        "ws-tuma": "ws-send"
      },
      events: {
        "tafuta": "search",
        "bonyeza": "click",
        "panya_shuka": "mousedown",
        "panya_juu": "mouseup",
        "panya_ingia": "mouseenter",
        "panya_toka": "mouseleave",
        "panya_nje": "mouseout",
        "panya_sogea": "mousemove",
        "kitufe_shuka": "keydown",
        "kitufe_juu": "keyup",
        "lenga": "focus",
        "kubadilisha": "change",
        "ingizo": "input",
        "wasilisha": "submit",
        "pakia": "load",
        "shuka": "unload",
        "badilisha_ukubwa": "resize",
        "sogeza": "scroll",
        "bonyeza_mara_mbili": "dblclick",
        "kitufe_bonyeza": "keypress",
        "zingatia": "focus",
        "poteza_macho": "blur",
        "badilisha": "change",
        "weka_upya": "reset",
        "gusa_anza": "touchstart",
        "gusa_mwisho": "touchend",
        "gusa_sogea": "touchmove",
        "gusa_ghairi": "touchcancel"
      },
    },
  });
})();
