// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: th
// Re-generate after editing packages/core/scripts/htmx-attr-vocab.mjs,
// packages/semantic/src/generators/profiles/thai.ts
// or packages/i18n/src/dictionaries/th.ts.
// Several names may map to one canonical: the first is the primary (the form
// to teach), later ones are aliases kept so already-authored pages still work.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "th" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('th', {
    hyperfixi: {
      attrs: {
        "hx-รับค่า": "hx-get",
        "hx-โพสต์": "hx-post",
        "hx-ใส่": "hx-put",
        "hx-ลบ": "hx-delete",
        "hx-เป้าหมาย": "hx-target",
        "hx-สลับที่": "hx-swap",
        "hx-สลับ": "hx-swap",
        "hx-ทริกเกอร์": "hx-trigger",
        "hx-ยืนยัน": "hx-confirm",
        "hx-เร่ง": "hx-boost",
        "hx-ค่า": "hx-vals",
        "hx-ดัน-url": "hx-push-url",
        "hx-เมื่อ": "hx-on",
        "hx-ไลฟ์": "hx-live",
        "hx-ตัวบ่งชี้": "hx-indicator",
        "hx-รวม": "hx-include",
        "hx-เลือก": "hx-select",
        "hx-สลับที่-oob": "hx-swap-oob",
        "hx-ซิงค์": "hx-sync",
        "sse-เชื่อมต่อ": "sse-connect",
        "sse-สลับที่": "sse-swap",
        "sse-สลับ": "sse-swap",
        "ws-เชื่อมต่อ": "ws-connect",
        "ws-ส่ง": "ws-send"
      },
      events: {
        "ค้นหา": "search",
        "เมาส์เข้ามา": "mouseenter",
        "คลิก": "click",
        "เปลี่ยนแปลง": "change",
        "อินพุต": "input",
        "ส่ง": "submit",
        "โหลด": "load",
        "โฟกัส": "focus",
        "เบลอ": "blur",
        "รีเซ็ต": "reset",
        "กดคีย์": "keydown",
        "ปล่อยคีย์": "keyup",
        "เมาส์เข้า": "mouseover",
        "เมาส์ออก": "mouseout",
        "เลื่อน": "scroll",
        "ปรับขนาด": "resize",
        "ทุก": "every"
      },
    },
  });
})();
