// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: th
// Re-generate after editing packages/semantic/src/generators/profiles/thai.ts
// or packages/i18n/src/dictionaries/th.ts.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "th" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('th', {
    hyperfixi: {
      attrs: {
        "hx-รับค่า": "hx-get",
        "hx-ใส่": "hx-put",
        "hx-เป้าหมาย": "hx-target",
        "hx-สลับที่": "hx-swap",
        "hx-ทริกเกอร์": "hx-trigger",
        "hx-เมื่อ": "hx-on",
        "hx-ไลฟ์": "hx-live",
        "sse-เชื่อมต่อ": "sse-connect",
        "sse-สลับที่": "sse-swap",
        "ws-เชื่อมต่อ": "ws-connect",
        "ws-ส่ง": "ws-send"
      },
      events: {
        "คลิก": "click",
        "เปลี่ยนแปลง": "change",
        "อินพุต": "input",
        "ส่ง": "submit",
        "โหลด": "load",
        "โฟกัส": "focus",
        "เบลอ": "blur",
        "รีเซ็ต": "reset",
        "กดคีย์": "keydown",
        "ปล่อยคีย์": "keyup",
        "เมาส์เข้า": "mouseover",
        "เมาส์ออก": "mouseout",
        "เลื่อน": "scroll",
        "ปรับขนาด": "resize",
        "ทุก": "every"
      },
    },
  });
})();
