// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: tl
// Re-generate after editing packages/semantic/src/generators/profiles/tagalog.ts
// or packages/i18n/src/dictionaries/tl.ts.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "tl" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('tl', {
    hyperfixi: {
      attrs: {
        "hx-kunin": "hx-get",
        "hx-ilagay": "hx-put",
        "hx-palitan_pwesto": "hx-swap",
        "hx-palitawin": "hx-trigger",
        "hx-kapag": "hx-on",
        "sse-ikonekta": "sse-connect",
        "sse-palitan_pwesto": "sse-swap",
        "ws-ikonekta": "ws-connect",
        "ws-ipadala": "ws-send"
      },
      events: {
        "bawat": "every"
      },
    },
  });
})();
