// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: tl
// Re-generate after editing packages/core/scripts/htmx-attr-vocab.mjs,
// packages/semantic/src/generators/profiles/tagalog.ts
// or packages/i18n/src/dictionaries/tl.ts.
// Several names may map to one canonical: the first is the primary (the form
// to teach), later ones are aliases kept so already-authored pages still work.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "tl" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('tl', {
    hyperfixi: {
      attrs: {
        "hx-kunin": "hx-get",
        "hx-ilathala": "hx-post",
        "hx-ilagay": "hx-put",
        "hx-burahin": "hx-delete",
        "hx-palit": "hx-swap",
        "hx-palitan_pwesto": "hx-swap",
        "hx-pampukaw": "hx-trigger",
        "hx-palitawin": "hx-trigger",
        "hx-kumpirmahin": "hx-confirm",
        "hx-pabilisin": "hx-boost",
        "hx-halaga": "hx-vals",
        "hx-itulak-url": "hx-push-url",
        "hx-kapag": "hx-on",
        "hx-indikador": "hx-indicator",
        "hx-isama": "hx-include",
        "hx-pilian": "hx-select",
        "hx-palit-oob": "hx-swap-oob",
        "hx-pagsabay": "hx-sync",
        "sse-ikonekta": "sse-connect",
        "sse-palit": "sse-swap",
        "sse-palitan_pwesto": "sse-swap",
        "ws-ikonekta": "ws-connect",
        "ws-ipadala": "ws-send"
      },
      events: {
        "pindot": "click",
        "bitaw-tiklado": "keyup",
        "pagbabago": "change",
        "karga": "load",
        "pasok-mouse": "mouseenter",
        "hanap": "search",
        "bawat": "every"
      },
    },
  });
})();
