// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: tr
// Re-generate after editing packages/semantic/src/generators/profiles/turkish.ts
// or packages/i18n/src/dictionaries/tr.ts.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "tr" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('tr', {
    hyperfixi: {
      attrs: {
        "hx-al": "hx-get",
        "hx-koy": "hx-put",
        "hx-hedef": "hx-target",
        "hx-takas": "hx-swap",
        "hx-tetikle": "hx-trigger",
        "hx-üzerinde": "hx-on",
        "hx-canlı": "hx-live",
        "sse-bağlan": "sse-connect",
        "sse-takas": "sse-swap",
        "ws-bağlan": "ws-connect",
        "ws-gönder": "ws-send"
      },
      events: {
        "tıklama": "click",
        "çift_tıklama": "dblclick",
        "fare_bas": "mousedown",
        "fare_bırak": "mouseup",
        "fare_gir": "mouseenter",
        "fare_çık": "mouseleave",
        "fare_üstü": "mouseover",
        "fare_dışı": "mouseout",
        "fare_hareket": "mousemove",
        "tuş_bas": "keydown",
        "tuş_bırak": "keyup",
        "tuş_basım": "keypress",
        "odak": "focus",
        "bulanık": "blur",
        "değişim": "change",
        "giriş": "input",
        "gönder": "submit",
        "sıfırla": "reset",
        "yükle": "load",
        "yükle_kaldır": "unload",
        "boyut_değiştir": "resize",
        "kaydır": "scroll",
        "dokunma_başla": "touchstart",
        "dokunma_bitir": "touchend",
        "dokunma_hareket": "touchmove",
        "dokunma_iptal": "touchcancel"
      },
    },
  });
})();
