// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: tr
// Re-generate after editing packages/core/scripts/htmx-attr-vocab.mjs,
// packages/semantic/src/generators/profiles/turkish.ts
// or packages/i18n/src/dictionaries/tr.ts.
// Several names may map to one canonical: the first is the primary (the form
// to teach), later ones are aliases kept so already-authored pages still work.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "tr" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('tr', {
    hyperfixi: {
      attrs: {
        "hx-al": "hx-get",
        "hx-gönder": "hx-post",
        "hx-koy": "hx-put",
        "hx-sil": "hx-delete",
        "hx-hedef": "hx-target",
        "hx-değiştirme": "hx-swap",
        "hx-takas": "hx-swap",
        "hx-tetikleyici": "hx-trigger",
        "hx-tetikle": "hx-trigger",
        "hx-onayla": "hx-confirm",
        "hx-hızlandır": "hx-boost",
        "hx-değerler": "hx-vals",
        "hx-itele-url": "hx-push-url",
        "hx-üzerinde": "hx-on",
        "hx-canlı": "hx-live",
        "hx-gösterge": "hx-indicator",
        "hx-içer": "hx-include",
        "hx-seçim": "hx-select",
        "hx-değiştirme-oob": "hx-swap-oob",
        "hx-eşitle": "hx-sync",
        "sse-bağlan": "sse-connect",
        "sse-değiştirme": "sse-swap",
        "sse-takas": "sse-swap",
        "ws-bağlan": "ws-connect",
        "ws-gönder": "ws-send"
      },
      events: {
        "arama": "search",
        "tıklama": "click",
        "farebas": "mousedown",
        "farebırak": "mouseup",
        "fareiçinde": "mouseover",
        "faredışında": "mouseout",
        "tuşbasma": "keydown",
        "tuşbırakma": "keyup",
        "odak": "focus",
        "bulanık": "blur",
        "değişim": "change",
        "giriş": "input",
        "gönderme": "submit",
        "sıfırla": "reset",
        "yükle": "load",
        "boyutlandırma": "resize",
        "kaydır": "scroll",
        "çift_tıklama": "dblclick",
        "fare_bas": "mousedown",
        "fare_bırak": "mouseup",
        "fare_gir": "mouseenter",
        "fare_çık": "mouseleave",
        "fare_üstü": "mouseover",
        "fare_dışı": "mouseout",
        "fare_hareket": "mousemove",
        "tuş_bas": "keydown",
        "tuş_bırak": "keyup",
        "tuş_basım": "keypress",
        "gönder": "submit",
        "yükle_kaldır": "unload",
        "boyut_değiştir": "resize",
        "dokunma_başla": "touchstart",
        "dokunma_bitir": "touchend",
        "dokunma_hareket": "touchmove",
        "dokunma_iptal": "touchcancel"
      },
    },
  });
})();
