// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: uk
// Re-generate after editing packages/semantic/src/generators/profiles/ukrainian.ts
// or packages/i18n/src/dictionaries/uk.ts.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "uk" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('uk', {
    hyperfixi: {
      attrs: {
        "hx-отримати": "hx-get",
        "hx-покласти": "hx-put",
        "hx-ціль": "hx-target",
        "hx-поміняти": "hx-swap",
        "hx-ініціювати": "hx-trigger",
        "hx-при": "hx-on",
        "hx-наживо": "hx-live",
        "sse-підключити": "sse-connect",
        "sse-поміняти": "sse-swap",
        "ws-підключити": "ws-connect",
        "ws-надіслати": "ws-send"
      },
      events: {
        "клік": "click",
        "подвійний_клік": "dblclick",
        "миша_вниз": "mousedown",
        "миша_вгору": "mouseup",
        "миша_вхід": "mouseenter",
        "миша_вихід": "mouseleave",
        "наведення": "mouseover",
        "відведення": "mouseout",
        "рух_миші": "mousemove",
        "клавіша_вниз": "keydown",
        "клавіша_вгору": "keyup",
        "натискання_клавіші": "keypress",
        "фокус": "focus",
        "розфокус": "blur",
        "зміна": "change",
        "введення": "input",
        "надсилання": "submit",
        "скидання": "reset",
        "завантаження": "load",
        "вивантаження": "unload",
        "зміна_розміру": "resize",
        "прокрутка": "scroll",
        "дотик_початок": "touchstart",
        "дотик_кінець": "touchend",
        "дотик_рух": "touchmove",
        "дотик_скасування": "touchcancel"
      },
    },
  });
})();
