// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: uk
// Re-generate after editing packages/core/scripts/htmx-attr-vocab.mjs,
// packages/semantic/src/generators/profiles/ukrainian.ts
// or packages/i18n/src/dictionaries/uk.ts.
// Several names may map to one canonical: the first is the primary (the form
// to teach), later ones are aliases kept so already-authored pages still work.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "uk" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('uk', {
    hyperfixi: {
      attrs: {
        "hx-отримати": "hx-get",
        "hx-опублікувати": "hx-post",
        "hx-покласти": "hx-put",
        "hx-видалити": "hx-delete",
        "hx-ціль": "hx-target",
        "hx-обмін": "hx-swap",
        "hx-поміняти": "hx-swap",
        "hx-тригер": "hx-trigger",
        "hx-ініціювати": "hx-trigger",
        "hx-підтвердити": "hx-confirm",
        "hx-прискорити": "hx-boost",
        "hx-значення": "hx-vals",
        "hx-історія-url": "hx-push-url",
        "hx-при": "hx-on",
        "hx-наживо": "hx-live",
        "hx-індикатор": "hx-indicator",
        "hx-включити": "hx-include",
        "hx-вибір": "hx-select",
        "hx-обмін-oob": "hx-swap-oob",
        "hx-синхронізація": "hx-sync",
        "sse-підключити": "sse-connect",
        "sse-обмін": "sse-swap",
        "sse-поміняти": "sse-swap",
        "ws-підключити": "ws-connect",
        "ws-надіслати": "ws-send"
      },
      events: {
        "пошук": "search",
        "клік": "click",
        "подвійний_клік": "dblclick",
        "мишавниз": "mousedown",
        "мишавгору": "mouseup",
        "миша_вхід": "mouseenter",
        "миша_вихід": "mouseleave",
        "наведення": "mouseover",
        "відведення": "mouseout",
        "рух_миші": "mousemove",
        "клавіша_вниз": "keydown",
        "клавіша_вгору": "keyup",
        "натискання_клавіші": "keypress",
        "фокус": "focus",
        "розфокус": "blur",
        "зміна": "change",
        "введення": "input",
        "надсилання": "submit",
        "скинути": "reset",
        "завантаження": "load",
        "вивантаження": "unload",
        "змінарозміру": "resize",
        "прокрутка": "scroll",
        "дотик_початок": "touchstart",
        "дотик_кінець": "touchend",
        "дотик_рух": "touchmove",
        "дотик_скасування": "touchcancel",
        "миша_вниз": "mousedown",
        "миша_вгору": "mouseup",
        "скидання": "reset",
        "зміна_розміру": "resize"
      },
    },
  });
})();
