// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: vi
// Re-generate after editing packages/semantic/src/generators/profiles/vietnamese.ts
// or packages/i18n/src/dictionaries/vi.ts.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "vi" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('vi', {
    hyperfixi: {
      attrs: {
        "hx-lấy giá trị": "hx-get",
        "hx-đặt": "hx-put",
        "hx-mục tiêu": "hx-target",
        "hx-hoán đổi": "hx-swap",
        "hx-kích hoạt": "hx-trigger",
        "hx-khi": "hx-on",
        "hx-trực-tiếp": "hx-live",
        "sse-kết-nối": "sse-connect",
        "sse-hoán đổi": "sse-swap",
        "ws-kết-nối": "ws-connect",
        "ws-gửi": "ws-send"
      },
      events: {
        "nhấp": "click",
        "nhấp đúp": "dblclick",
        "nhập": "input",
        "thay đổi": "change",
        "gửi": "submit",
        "phím xuống": "keydown",
        "phím lên": "keyup",
        "nhấn phím": "keypress",
        "chuột vào": "mouseenter",
        "chuột ra": "mouseout",
        "chuột rời": "mouseleave",
        "tập trung": "focus",
        "mất tập trung": "blur",
        "đặt-lại": "reset",
        "tải": "load",
        "cuộn": "scroll",
        "đổi kích thước": "resize"
      },
    },
  });
})();
