// Auto-generated by packages/core/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx-compat attribute vocab for language: zh
// Re-generate after editing packages/semantic/src/generators/profiles/chinese.ts
// or packages/i18n/src/dictionaries/zh.ts.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[hyperfixi-i18n] Vocab for "zh" loaded before the htmx-compat orchestrator. ' +
          'Move the hyperfixi-hx-v4 (or core) <script> above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('zh', {
    hyperfixi: {
      attrs: {
        "hx-获取": "hx-get",
        "hx-放置": "hx-put",
        "hx-目标": "hx-target",
        "hx-交换": "hx-swap",
        "hx-触发": "hx-trigger",
        "hx-当": "hx-on",
        "hx-实时": "hx-live",
        "sse-连接": "sse-connect",
        "sse-交换": "sse-swap",
        "ws-连接": "ws-connect",
        "ws-发送": "ws-send"
      },
      events: {
        "点击": "click",
        "双击": "dblclick",
        "鼠标按下": "mousedown",
        "鼠标抬起": "mouseup",
        "鼠标进入": "mouseenter",
        "鼠标离开": "mouseleave",
        "鼠标悬停": "mouseover",
        "鼠标移出": "mouseout",
        "鼠标移动": "mousemove",
        "按键按下": "keydown",
        "按键抬起": "keyup",
        "按键": "keypress",
        "聚焦": "focus",
        "失焦": "blur",
        "改变": "change",
        "输入": "input",
        "提交": "submit",
        "重置": "reset",
        "加载": "load",
        "卸载": "unload",
        "调整大小": "resize",
        "滚动": "scroll",
        "触摸开始": "touchstart",
        "触摸结束": "touchend",
        "触摸移动": "touchmove",
        "触摸取消": "touchcancel"
      },
    },
  });
})();
