// Auto-generated by packages/htmx-adapter/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx attribute vocab for language: en
// Re-generate after editing packages/htmx-adapter/scripts/htmx-attr-vocab.mjs,
// packages/semantic/src/generators/profiles/english.ts
// or packages/i18n/src/dictionaries/en.ts.
// Several names may map to one canonical: the first is the primary (the form
// to teach), later ones are aliases kept so already-authored pages still work.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[htmx-i18n] Vocab for "en" loaded before its registry. ' +
          'Move the @lokascript/htmx-adapter <script> (htmx-i18n.global.js) above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('en', {
    hyperfixi: {
      attrs: {},
      events: {},
    },
  });
})();
