// Auto-generated by packages/htmx-adapter/scripts/gen-htmx-vocab.mjs — do not edit by hand.
// Localized htmx attribute vocab for language: pl
// Re-generate after editing packages/htmx-adapter/scripts/htmx-attr-vocab.mjs,
// packages/semantic/src/generators/profiles/polish.ts
// or packages/i18n/src/dictionaries/pl.ts.
// Several names may map to one canonical: the first is the primary (the form
// to teach), later ones are aliases kept so already-authored pages still work.
(function () {
  if (typeof window === 'undefined' || !window.__hyperfixi_i18n) {
    if (typeof console !== 'undefined') {
      console.warn(
        '[htmx-i18n] Vocab for "pl" loaded before its registry. ' +
          'Move the @lokascript/htmx-adapter <script> (htmx-i18n.global.js) above the vocab <script>.'
      );
    }
    return;
  }
  window.__hyperfixi_i18n.register('pl', {
    hyperfixi: {
      attrs: {
        "hx-uzyskaj": "hx-get",
        "hx-opublikuj": "hx-post",
        "hx-umieść": "hx-put",
        "hx-usuń": "hx-delete",
        "hx-cel": "hx-target",
        "hx-zamiana": "hx-swap",
        "hx-zamień": "hx-swap",
        "hx-wyzwalacz": "hx-trigger",
        "hx-wyzwól": "hx-trigger",
        "hx-potwierdź": "hx-confirm",
        "hx-przyspiesz": "hx-boost",
        "hx-wartości": "hx-vals",
        "hx-historia-url": "hx-push-url",
        "hx-gdy": "hx-on",
        "hx-na-żywo": "hx-live",
        "hx-wskaźnik": "hx-indicator",
        "hx-dołącz": "hx-include",
        "hx-wybór": "hx-select",
        "hx-zamiana-oob": "hx-swap-oob",
        "hx-synchronizacja": "hx-sync",
        "sse-połącz": "sse-connect",
        "sse-zamiana": "sse-swap",
        "sse-zamień": "sse-swap",
        "ws-połącz": "ws-connect",
        "ws-wyślij": "ws-send"
      },
      events: {
        "szukaj": "search",
        "kliknięcie": "click",
        "podwójnekliknięcie": "dblclick",
        "myszwejście": "mouseenter",
        "myszwyjście": "mouseleave",
        "mysznad": "mouseover",
        "myszpoza": "mouseout",
        "myszruch": "mousemove",
        "klawiszdół": "keydown",
        "klawiszgóra": "keyup",
        "klawisznaciśnięcie": "keypress",
        "fokus": "focus",
        "rozmycie": "blur",
        "zmiana": "change",
        "wejście": "input",
        "wysłaniu": "submit",
        "zresetuj": "reset",
        "załaduj": "load",
        "wyładuj": "unload",
        "przewiń": "scroll",
        "dotykstart": "touchstart",
        "dotykkoniec": "touchend",
        "dotykruch": "touchmove",
        "dotykanuluj": "touchcancel",
        "myszdół": "mousedown",
        "myszgóra": "mouseup",
        "wyślij": "submit",
        "resetuj": "reset",
        "zmieńrozmiar": "resize"
      },
    },
  });
})();
